### ISSUE TITLE
About PhotoShape...

### ISSUE THREAD

**Issue by VivianGemLee** [XiangyuSu611/3D-Renderer-for-Mask-Image#2]
Hi,xiangyu.Racently I know photoshape and I think I can use it in my work now.But I have some stupid questions about it.I notice that you may have some experience about photoshape,can we talk for a while?I don't know your email or Wechat..

**Comment by XiangyuSu611** [comment]
ok. this is my wechat: sxy_nihaoa or my gmail xiangyv.su@gmail.com :)
